apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-bot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ipfs-bot
  template:
    metadata:
      labels:
        app: ipfs-bot
    spec:
      containers:
        - name: ipfs-bot
          image: localhost:5000/ipfs-bot:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: NATS_ENDPOINT
              value: nats://ipfs-telemetry-nats:4222
