apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
        app.kubernetes.io/component: monitor
    spec:
      containers:
        - name: monitor
          image: localhost:5000/monitor:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: NATS_ENDPOINT
              value: nats://ipfs-telemetry-nats:4222
            - name: MONITOR_COLLECT_INTERVAL
              value: "15s"
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
