{
 "title": "Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monitor_active_peers_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Exports",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(monitor_exports_ratio_total[5m]))",
     "legendFormat": "Exports"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[2m])*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}