{
 "title": "Network View",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "High Water",
     "type": "stat",
     "gridPos": { "h": 13, "w": 2, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.95, libp2p_network_high_water)",
       "legendFormat": "95th percentile"
      },
      { "expr": "avg(libp2p_network_high_water)", "legendFormat": "Average" },
      {
       "expr": "quantile(0.05, libp2p_network_high_water)",
       "legendFormat": "5th percentile"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "stat",
     "gridPos": { "h": 13, "w": 2, "x": 2, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.95, libp2p_network_connections)",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "avg(libp2p_network_connections)",
       "legendFormat": "Average"
      },
      {
       "expr": "quantile(0.05, libp2p_network_connections)",
       "legendFormat": "5th percentile"
      }
     ]
    },
    {
     "title": "Low Water",
     "type": "stat",
     "gridPos": { "h": 13, "w": 2, "x": 4, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.95, libp2p_network_low_water)",
       "legendFormat": "95th percentile"
      },
      { "expr": "avg(libp2p_network_low_water)", "legendFormat": "Average" },
      {
       "expr": "quantile(0.05, libp2p_network_low_water)",
       "legendFormat": "5th percentile"
      }
     ]
    },
    {
     "title": "Total Incoming Traffic",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 9, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(avg(libp2p_network_total_in{protocol!=\"\"}) by (protocol))/sum(avg(libp2p_network_total_in{protocol!=\"\"}) by (protocol))",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Incoming Traffic",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 9, "x": 15, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(avg(libp2p_network_total_in{protocol!=\"\"}) by (protocol))/sum(avg(libp2p_network_total_in{protocol!=\"\"}) by (protocol))",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Rate Outgoing Traffic",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(avg(libp2p_network_rate_out{protocol!=\"\"}[30m]) by (protocol))/sum(avg(libp2p_network_rate_out{protocol!=\"\"}[30m]) by (protocol))",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Rate Incoming Traffic",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(avg(libp2p_network_rate_in{protocol!=\"\"}[30m]) by (protocol))/sum(avg(libp2p_network_rate_in{protocol!=\"\"}[30m]) by (protocol))",
       "legendFormat": "{{protocol}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bitswap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Discovery Success Rate",
     "type": "gauge",
     "gridPos": { "h": 13, "w": 7, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bitswap_session_discovery_success[1h])/sum(bitswap_session_discovery_failure[1h]+bitswap_session_discovery_success[1h])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time to First Byte",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 17, "x": 7, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bitswap_session_time_to_first_block_bucket) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Incoming Messages",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(bitswap_client_messages_received[5m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "quantile(0.95, rate(bitswap_client_messages_received[5m]))",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "quantile(0.05, rate(bitswap_client_messages_received[5m]))",
       "legendFormat": "5th percentile"
      }
     ]
    },
    {
     "title": "Duplicate Blocks Received",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(bitswap_client_dup_blocks_received/bitswap_client_blocks_received)",
       "legendFormat": "Average"
      },
      {
       "expr": "quantile(0.95, bitswap_client_dup_blocks_received/bitswap_client_blocks_received)",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "quantile(0.05, bitswap_client_dup_blocks_received/bitswap_client_blocks_received)",
       "legendFormat": "5th percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Kademlia",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "FindNode Latency",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kad_outbound_request_latency_bucket{message_type=\"FindNode\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "GetProviders Latency",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kad_outbound_request_latency_bucket{message_type=\"GetProviders\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "PutValue Latency",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kad_outbound_request_latency_bucket{message_type=\"PutValue\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Messages Sent",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(kad_sent_requests[5m])) by (message_type)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Used",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "avg(ipfs_storage_used)", "legendFormat": "Average" },
      {
       "expr": "quantile(0.95, ipfs_storage_used)",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "quantile(0.05, ipfs_storage_used)",
       "legendFormat": "5th percentile"
      }
     ]
    },
    { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 } },
    {
     "title": "Storage Used",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(ipfs_storage_used/ipfs_storage_total)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}