{
 "title": "World View",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 } },
  {
   "title": "World Distribution",
   "type": "geomap",
   "gridPos": { "h": 24, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH peer_latest  AS (\n  SELECT peer, MAX(timestamp) timestamp\n  FROM discovery\n  WHERE timestamp >= $__timeFrom() AND timestamp <= $__timeTo()\n  GROUP BY peer\n)\nSELECT discovery.peer, latitude, longitude\nFROM discovery\nJOIN peer_latest ON (discovery.peer = peer_latest.peer) AND (discovery.timestamp = peer_latest.timestamp);"
    }
   ]
  },
  {
   "title": "Active Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(monitor_active_peers_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer List",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH peer_latest  AS (\n  SELECT peer, MAX(timestamp) timestamp\n  FROM discovery\n  WHERE timestamp >= $__timeFrom() AND timestamp <= $__timeTo()\n  GROUP BY peer\n)\nSELECT discovery.peer \"PeerID\", location \"Location\", discovery.timestamp \"Last Seen\"\nFROM discovery\nJOIN peer_latest ON (discovery.peer = peer_latest.peer) AND (discovery.timestamp = peer_latest.timestamp)\nORDER BY discovery.timestamp DESC;"
    }
   ]
  }
 ]
}