{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "crawler_peers_current_crawl", "legendFormat": "Current Crawl" },
    { "expr": "crawler_peers_last_crawl", "legendFormat": "Last Crawl" }
   ]
  },
  {
   "title": "Peer Distribution",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"crawler\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"location\" and r[\"_value\"] != \"s00000000000\")"
    }
   ]
  },
  {
   "title": "Telemetry Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crawler_peers_telemetry_current_crawl",
     "legendFormat": "Current Crawl"
    },
    {
     "expr": "crawler_peers_telemetry_last_crawl",
     "legendFormat": "Last Crawl"
    }
   ]
  },
  {
   "title": "Crawls",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "crawler_completed_crawls" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "crawler_errors_current_crawl", "legendFormat": "Current Crawl" },
    { "expr": "crawler_errors_last_crawl", "legendFormat": "Last Crawl" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes" }
   ]
  }
 ]
}