{
 "title": "Peer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "peer" }
  ]
 },
 "panels": [
  {
   "title": "Bitswap",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bitswap\" and r[\"peer\"] == \"${peer}\")\n  |> drop(columns: [\"peer\", \"session\"])"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_conns\" and r[\"peer\"] == \"${peer}\")\n  |> drop(columns: [\"peer\", \"session\"])\n"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_stats\")\n  |> filter(fn: (r) => r[\"peer\"] == \"${peer}\")\n  |> toFloat()\n  |> group(columns: [\"peer\", \"_time\", \"_field\"])\n  |> sum()\n  |> drop(columns: [\"peer\"])\n  |> group(columns: [\"_field\"])"
    }
   ]
  },
  {
   "title": "Kademlia Handlers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kademlia_handler\")\n  |> filter(fn: (r) => r[\"peer\"] == \"${peer}\")\n  |> group(columns: [\"peer\", \"type\"])\n  |> aggregateWindow(every: 5s, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"resources\" and r[\"peer\"] == \"${peer}\")\n  |> drop(columns: [\"peer\", \"session\"])"
    }
   ]
  }
 ]
}