scrape_configs:
  - job_name: server
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:2112
  - job_name: crawler
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:2113
  - job_name: daemon
    scrape_interval: 5s
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets:
        - localhost:5001
