# NATS: https://cncf-branding.netlify.app/img/projects/nats/icon/color/nats-icon-color.svg
# S3: https://icons.terrastruct.com/aws/Storage/Amazon-Simple-Storage-Service-S3_Bucket_light-bg.svg
# Prometheus: https://cncf-branding.netlify.app/img/projects/prometheus/icon/color/prometheus-icon-color.svg
# Timescale: https://www.timescale.com/static/170c20ad89a8d3596d754d8ed6f5cb22/TimescaleLogoSocialMedia1Svg.svg
# Grafana: https://upload.wikimedia.org/wikipedia/commons/a/a1/Grafana_logo.svg

internet: internet {
  shape: cloud
}

monitor: monitor

crawler: crawler

s3-telemetry: telemetry {
  icon: https://icons.terrastruct.com/aws/Storage/Amazon-Simple-Storage-Service-S3_Bucket_light-bg.svg
}

nats-discovery: discovery {
  icon: https://cncf-branding.netlify.app/img/projects/nats/icon/color/nats-icon-color.svg
}

nats-telemetry: telemetry {
  icon: https://cncf-branding.netlify.app/img/projects/nats/icon/color/nats-icon-color.svg
}

webapi: webapi

exporters: exporters {
}

grafana: Grafana {
  icon: https://upload.wikimedia.org/wikipedia/commons/a/a1/Grafana_logo.svg
}

crawler -- internet: crawl DHT
crawler -> nats-discovery: publish discovered peers

monitor <- nats-discovery: subscribe to discovered peers
monitor <- internet: monitor peers
monitor -> s3-telemetry: store collected telemetry
monitor -> nats-telemetry: publish object key of stored telemetry

webapi -> nats-discovery: POST /api/v1/discovery
webapi <- s3-telemetry: GET /api/v1/telemetry

exporters <- nats-discovery: subscribe to discovered peers
exporters <- nats-telemetry: subscribe to telemetry
exporters <- s3-telemetry: fetch telemetry

grafana <- exporters