apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ipfs-telemetry
resources:
  - namespace.yaml
  - nats.yaml
  - pg.yaml
  - vm.yaml
  - crawler.yaml
  - monitor.yaml
  - grafana.yaml
  - vm-otlp-exporter.yaml
  - pg-crawler-exporter.yaml
  - pg-monitor-exporter.yaml
