apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
        app.kubernetes.io/name: monitor
    spec:
      containers:
        - name: monitor
          image: ghcr.io/diogo464/ipfs-telemetry/backend:latest
          args: ["monitor"]
          env:
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: VM_URL
              value: "http://vm:8428"
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-pg
                  key: DATABASE_URL
            - name: MONITOR_COLLECT_INTERVAL
              value: "5s"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: "64Mi"
              cpu: "0"
            limits:
              memory: "256Mi"
              cpu: "1"
          ports:
            - name: prometheus
              containerPort: 9090
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

