apiVersion: infra.d464.sh/v1
kind: Postgres
metadata:
  name: postgres
spec:
  tag: "17"
  replicas: 1 # this value is optional and can be 1 or 0
  resources:
    requests:
      memory: "1Gi"
      cpu: "100m"
    limits:
      memory: "2Gi"
      cpu: "2"
  storage:
    size: 20Gi
    storageClassName: blackmesa
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  labels:
    app.kubernetes.io/name: postgres-lb
  annotations:
    service.infra.d464.sh/domain: "ipfs-pg.d464.sh"
spec:
  type: LoadBalancer
  selector:
    app: postgres-pg
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
