{{- if .Values.grafana.enabled -}}
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ .Release.Name }}-grafana-datasource
  labels:
    {{- include "ipfs-telemetry.labels" . | nindent 4 }}
spec:
  name: {{ .Release.Name }}-tsdb
  datasources:
  - name: Postgres
    type: postgres
    database: postgres # name of your database
    editable: false
    jsonData:
      connMaxLifetime: 14400
      maxIdleConns: 2
      maxOpenConns: 0
      postgresVersion: 1400
      sslmode: disable
      timescaledb: true
    secureJsonData:
      password: {{ .Values.timescaledb.secrets.credentials.PATRONI_SUPERUSER_PASSWORD }} # password of your user
    url: {{ .Release.Name }}-tsdb:5432
    user: postgres # user to access your database
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://{{ .Release.Name}}-vm-server:8428
    version: 1
    editable: false
    jsonData:
      tlsSkipVerify: true
      timeInterval: "5s"
{{- end }}