# https://github.com/timescale/helm-charts/issues/405#issuecomment-1298789521
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: timescale-patch
  labels:
    {{- include "ipfs-telemetry.labels" . | nindent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: timescale-patch-binding
  labels:
    {{- include "ipfs-telemetry.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-tsdb
  namespace: default
roleRef:
  kind: Role 
  name: timescale-patch
  apiGroup: rbac.authorization.k8s.io

