apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: grafana-prometheus
spec:
  name: prometheus
  datasources:
    - name: Prometheus
      isDefault: true
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      version: 1
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
