apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: grafana-timescaledb
spec:
  name: timescaledb
  datasources:
    - name: Postgres
      type: postgres
      database: postgres # name of your database
      editable: false
      jsonData:
        connMaxLifetime: 14400
        maxIdleConns: 2
        maxOpenConns: 0
        postgresVersion: 1400
        sslmode: disable
        timescaledb: true
      secureJsonData:
        password: postgres
      url: timescaledb:5432
      user: postgres
