apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ipfs-telemetry
# TODO: maybe add storageClass to timescaledb
# values:
#   persistentVolumes:
#     data:
#       size: 20Gi
#       storageClass: nfs-blackmesa-arch
resources:
  - namespace.yaml
  - ../../base
  - docs-ingress.yaml
images:
  - name: ghcr.io/diogo464/ipfs-telemetry/ipfs-bot
    newName: ghcr.io/diogo464/ipfs-telemetry/ipfs-bot # {"$imagepolicy": "ipfs-telemetry:ipfs-bot:name"}
    newTag: 0.5.1 # {"$imagepolicy": "ipfs-telemetry:ipfs-bot:tag"}
  - name: ghcr.io/diogo464/ipfs-telemetry/monitor
    newName: ghcr.io/diogo464/ipfs-telemetry/monitor # {"$imagepolicy": "ipfs-telemetry:monitor:name"}
    newTag: 0.5.1 # {"$imagepolicy": "ipfs-telemetry:monitor:tag"}
  - name: ghcr.io/diogo464/ipfs-telemetry/crawler
    newName: ghcr.io/diogo464/ipfs-telemetry/crawler # {"$imagepolicy": "ipfs-telemetry:crawler:name"}
    newTag: 0.5.1 # {"$imagepolicy": "ipfs-telemetry:crawler:tag"}
  - name: ghcr.io/diogo464/ipfs-telemetry/backend
    newName: ghcr.io/diogo464/ipfs-telemetry/backend # {"$imagepolicy": "ipfs-telemetry:backend:name"}
    newTag: 0.5.1 # {"$imagepolicy": "ipfs-telemetry:backend:tag"}
  - name: ghcr.io/diogo464/ipfs-telemetry/docs
    newName: ghcr.io/diogo464/ipfs-telemetry/docs # {"$imagepolicy": "ipfs-telemetry:docs:name"}
    newTag: 0.5.1 # {"$imagepolicy": "ipfs-telemetry:docs:tag"}
components:
  # Dependencies
  - ../../components/dependencies/repos
  - ../../components/dependencies/redis
  - ../../components/dependencies/nats
  - ../../components/dependencies/victoria-metrics
  - ../../components/dependencies/timescaledb
  # Currently there is not support for Grafana CRDs in namespaces other than the one where the operator is installed.
  # https://github.com/grafana-operator/grafana-operator/blob/master/documentation/multi_namespace_support.md
  - ../../components/dependencies/grafana-operator
  # Application Components
  - ../../components/ipfs-bot
  - ../../components/grafana
  - ../../components/prometheus
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: ipfs-bot
patchesStrategicMerge:
  - patch-monitor-collect-interval.yaml
  - patch-grafana-ingress.yaml
  - patch-nats.yaml
  - patch-timescaledb.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: ipfs-telemetry
      app.kubernetes.io/instance: ipfs-telemetry-main
