apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: timescaledb
spec:
  values:
    resources:
      requests:
        cpu: 150m
        memory: 128Mi
      limits:
        cpu: 350m
        memory: 256Mi
