{
 "title": "Crawler",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "database", "label": "Database", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Total Crawls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM crawler.crawl;"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Crawl/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 3600.0 / AVG(EXTRACT(EPOCH FROM timestamp_end - timestamp_begin)) FROM crawler.crawl;"
    }
   ]
  },
  {
   "title": "Current Crawl Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH time_buckets AS (\n  SELECT\n    $__timeGroup(timestamp, '30s') AS time,\n    COUNT(peer_id) AS count\n  FROM\n    crawler.peer\n  WHERE\n    crawl IS NULL AND $__timeFilter(timestamp)\n  GROUP BY\n    time\n)\nSELECT\n  time,\n  SUM(count) OVER (ORDER BY time) AS cumulative_count\nFROM\n  time_buckets\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Current Crawl Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(peer_id) FROM crawler.peer WHERE crawl IS NULL;"
    }
   ]
  },
  {
   "title": "Routing Table Size",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT dht_entries FROM crawler.peer WHERE crawl IS NULL;"
    }
   ]
  },
  {
   "title": "Autonomous Systems",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT asn_org, COUNT(*) AS count\nFROM crawler.peer\nWHERE crawl IS NULL\nGROUP BY asn_org\nORDER BY count DESC;\n"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT country, COUNT(*) AS n FROM crawler.peer WHERE crawl IS NULL GROUP BY country ORDER BY n DESC;"
    }
   ]
  },
  {
   "title": "Agent Versions",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS count,\n  agent\nFROM\n  crawler.peer\nWHERE\n  crawl IS NULL\nGROUP BY\n  agent\nORDER BY\n  count DESC\n"
    }
   ]
  },
  {
   "title": "Supported Protocols",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  protocol,\n  COUNT(*) AS count\nFROM (\n  SELECT UNNEST(protocols) AS protocol\n  FROM crawler.peer\n  WHERE crawl IS NULL\n) AS flattened\nGROUP BY protocol\nORDER BY count DESC\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, COUNT(*) FROM crawler.peer WHERE crawl IS NULL GROUP BY latitude,longitude;"
    }
   ]
  }
 ]
}