{
 "title": "Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "postgres", "label": "PostgreSQL", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Active Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monitor_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Peers",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM monitor.active;" }
   ]
  },
  {
   "title": "Exports",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(sum(monitor_peer_collect_success_total))[30s]",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(sum(monitor_peer_collect_failure_total))[30s]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Export Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(monitor_peer_collect_duration_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_time_seconds_total{service_name=\"monitor\", state=\"user\"})[10s] * 100",
     "legendFormat": "cpu"
    },
    {
     "expr": "process_runtime_go_mem_heap_alloc_bytes{service_name=\"monitor\"}",
     "legendFormat": "heap"
    }
   ]
  }
 ]
}