{
 "title": "Network View",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Core Counts",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "-- https://stackoverflow.com/questions/43527730/postgres-count-instances-and-put-in-buckets\nWITH buckets as (\n  SELECT (CASE WHEN cnt <= 2 THEN '<= 2'\n             WHEN cnt <= 4 THEN '<= 4'\n             WHEN cnt <= 8 THEN '<= 8'\n             WHEN cnt <= 16 THEN '<= 16'\n             ELSE '16+'\n        END) as bucket, COUNT(*) as n\n  FROM (\n    SELECT DISTINCT ON(peer) NULLIF(value, '')::int as cnt\n     FROM properties\n     WHERE name = 'process.runtime.numcpu'\n   ) l\n   GROUP BY bucket\n   ORDER BY MIN(cnt)\n ) SELECT bucket \"Cores\", (n / (SELECT SUM(n) FROM buckets)) \"Total\"\n FROM buckets;"
    }
   ]
  },
  {
   "title": "Architecture",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH architectures AS (\n  SELECT DISTINCT ON (peer) peer, value \"arch\"\n  FROM properties  where name = 'process.runtime.arch'\n)\nSELECT arch \"Architecture\", (COUNT(peer) / (SELECT COUNT(arch) FROM architectures)) \"Total\"\nFROM architectures GROUP BY arch;"
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH oss AS (\n  SELECT DISTINCT ON (peer) peer, value \"os\"\n  FROM properties  where name = 'process.runtime.os'\n)\nSELECT os \"OS\", (COUNT(peer) / (SELECT COUNT(os) FROM oss)) \"Total\"\nFROM oss GROUP BY os;"
    }
   ]
  },
  {
   "title": "Session Lifetime",
   "type": "histogram",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "-- https://stackoverflow.com/questions/14020919/find-difference-between-timestamps-in-seconds-in-postgresql\nWITH durations  AS (\n  SELECT sessions.session \"session\", (EXTRACT(EPOCH FROM sessions.last_seen) - NULLIF(properties.value, '')::int) \"dur\"\n  FROM sessions\n  INNER JOIN properties ON sessions.session = properties.session\n  WHERE properties.name = 'process.boottime'\n)\nSELECT session, MAX(dur) \"dur\" FROM durations GROUP BY session;"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "High Water",
     "type": "stat",
     "gridPos": { "h": 13, "w": 2, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.95, libp2p_network_high_water)",
       "legendFormat": "95th percentile"
      },
      { "expr": "avg(libp2p_network_high_water)", "legendFormat": "Average" },
      {
       "expr": "quantile(0.05, libp2p_network_high_water)",
       "legendFormat": "5th percentile"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "stat",
     "gridPos": { "h": 13, "w": 2, "x": 2, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.95, libp2p_network_connections)",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "avg(libp2p_network_connections)",
       "legendFormat": "Average"
      },
      {
       "expr": "quantile(0.05, libp2p_network_connections)",
       "legendFormat": "5th percentile"
      }
     ]
    },
    {
     "title": "Low Water",
     "type": "stat",
     "gridPos": { "h": 13, "w": 2, "x": 4, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.95, libp2p_network_low_water)",
       "legendFormat": "95th percentile"
      },
      { "expr": "avg(libp2p_network_low_water)", "legendFormat": "Average" },
      {
       "expr": "quantile(0.05, libp2p_network_low_water)",
       "legendFormat": "5th percentile"
      }
     ]
    },
    {
     "title": "Total Incoming Traffic",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 9, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(avg(libp2p_network_total_in{protocol!=\"\"}) by (protocol))/sum(avg(libp2p_network_total_in{protocol!=\"\"}) by (protocol))",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Incoming Traffic",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 9, "x": 15, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(avg(libp2p_network_total_in{protocol!=\"\"}) by (protocol))/sum(avg(libp2p_network_total_in{protocol!=\"\"}) by (protocol))",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Rate Outgoing Traffic",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(avg(libp2p_network_rate_out{protocol!=\"\"}[30m]) by (protocol))/sum(avg(libp2p_network_rate_out{protocol!=\"\"}[30m]) by (protocol))",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Rate Incoming Traffic",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(avg(libp2p_network_rate_in{protocol!=\"\"}[30m]) by (protocol))/sum(avg(libp2p_network_rate_in{protocol!=\"\"}[30m]) by (protocol))",
       "legendFormat": "{{protocol}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bitswap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Discovery Success Rate",
     "type": "gauge",
     "gridPos": { "h": 13, "w": 7, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bitswap_session_discovery_success[1h])/sum(bitswap_session_discovery_failure[1h]+bitswap_session_discovery_success[1h])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time to First Byte",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 17, "x": 7, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bitswap_session_time_to_first_block_bucket) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Incoming Messages",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(bitswap_client_messages_received[5m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "quantile(0.95, rate(bitswap_client_messages_received[5m]))",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "quantile(0.05, rate(bitswap_client_messages_received[5m]))",
       "legendFormat": "5th percentile"
      }
     ]
    },
    {
     "title": "Duplicate Blocks Received",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(bitswap_client_dup_blocks_received/bitswap_client_blocks_received)",
       "legendFormat": "Average"
      },
      {
       "expr": "quantile(0.95, bitswap_client_dup_blocks_received/bitswap_client_blocks_received)",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "quantile(0.05, bitswap_client_dup_blocks_received/bitswap_client_blocks_received)",
       "legendFormat": "5th percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Kademlia",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "FindNode Latency",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kad_outbound_request_latency_bucket{message_type=\"FindNode\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "GetProviders Latency",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kad_outbound_request_latency_bucket{message_type=\"GetProviders\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "PutValue Latency",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kad_outbound_request_latency_bucket{message_type=\"PutValue\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Messages Sent",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(kad_sent_requests[5m])) by (message_type)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Used",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "avg(ipfs_storage_used)", "legendFormat": "Average" },
      {
       "expr": "quantile(0.95, ipfs_storage_used)",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "quantile(0.05, ipfs_storage_used)",
       "legendFormat": "5th percentile"
      }
     ]
    },
    { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 } },
    {
     "title": "Storage Used",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(ipfs_storage_used/ipfs_storage_total)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}