apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  podMetadata:
    labels: {}
  podMonitorSelector:
    matchLabels:
      prometheus: prometheus
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
