services:
  crawler:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    command: crawler
    environment:
      CRAWLER_PROMETHEUS_ADDRESS: ":9090"
      CRAWLER_INFLUXDB_ADDRESS: "http://influxdb:8086"
      CRAWLER_INFLUXDB_TOKEN: "token"
      CRAWLER_INFLUXDB_ORG: "adc"
      CRAWLER_INFLUXDB_BUCKET: "crawler"
      CRAWLER_ADDRESS: ":5600"
    depends_on:
      - influxdb
      - prometheus
  monitor:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    command: monitor
    environment:
      MONITOR_PROMETHEUS_ADDRESS: ":9090"
      MONITOR_INFLUXDB_ADDRESS: "http://influxdb:8086"
      MONITOR_INFLUXDB_TOKEN: "token"
      MONITOR_INFLUXDB_ORG: "adc"
      MONITOR_INFLUXDB_BUCKET: "telemetry"
      MONITOR_ADDRESS: ":5600"
    depends_on:
      - influxdb
      - prometheus
  link:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    command: link
    environment:
      LINK_CRAWLER: "crawler:5600"
      LINK_MONITOR: "monitor:5600"
    depends_on:
      - crawler
      - monitor
  grafana:
    image: docker.io/grafana/grafana:latest
    volumes:
      - telemetry-grafana:/var/lib/grafana
      - ./grafana-datasources:/etc/grafana/provisioning/datasources/:Z
      - ./grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:Z
      - ./grafana-dashboards/:/var/lib/grafana/dashboards:Z
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
  influxdb:
    image: docker.io/influxdb:latest
    volumes:
      - telemetry-influxdb:/var/lib/influxdb2
      - ./influxdb_setup.sh:/docker-entrypoint-initdb.d/influxdb_setup.sh:Z
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "user"
      DOCKER_INFLUXDB_INIT_PASSWORD: "password"
      DOCKER_INFLUXDB_INIT_ORG: "adc"
      DOCKER_INFLUXDB_INIT_BUCKET: "telemetry"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "token"
  prometheus:
    image: docker.io/prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
volumes:
  telemetry-grafana: {}
  telemetry-influxdb: {}
