# https://github.com/timescale/helm-charts/issues/405#issuecomment-1298789521
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: timescale-patch
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: timescale-patch-binding
subjects:
  - kind: ServiceAccount
    name: timescaledb
roleRef:
  kind: Role
  name: timescale-patch
  apiGroup: rbac.authorization.k8s.io
