{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "Upload Speed",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 11, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"bandwidth\" and r._field == \"upload\")\n    |> drop(columns: [\"peer\", \"session\"])"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"bandwidth\" and r._field == \"download\")\n    |> drop(columns: [\"peer\", \"session\"])"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"session_info\")\n    |> unique(column: \"session\")\n    |> map(fn: (r) => ({\n        r with _value: (int(v: now()) - int(v: time(v: r._value))) / 1000000000\n    }))\n    |> group()\n    |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Kademlia Handlers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kademlia_handler\")\n  |> group(columns: [\"peer\", \"type\"])\n  |> aggregateWindow(every: duration(v: ( (uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)) / uint(v: 240) ) ), fn: mean)\n  |> drop(columns: [\"peer\", \"session\"])"
    }
   ]
  }
 ]
}