{
 "title": "Peer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "peer" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket: \"telemetry\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"system_info\" and r.peer == \"${peer}\")\n    |> schema.fieldsAsCols()\n    |> keep(columns: [\"os\", \"arch\", \"numcpu\", \"peer\", \"session\"])\n    |> limit(n: 1)\n    |> map(fn: (r) => {\n        original = r\n        bootTimeRecord = from(bucket: \"telemetry\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r._measurement == \"session_info\" and r.peer == original.peer and r.session == original.session)\n            |> schema.fieldsAsCols()\n            |> keep(columns: [\"boot_time\"])\n            |> limit(n: 1)\n            |> findRecord(fn: (key) => true, idx: 0)\n        return {r with boot_time: bootTimeRecord.boot_time}\n    })\n    |> drop(columns: [\"peer\", \"session\", \"boot_time\"])"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_conns\" and r[\"peer\"] == \"${peer}\")\n  |> drop(columns: [\"peer\", \"session\"])\n"
    },
    {
     "query": "from(bucket: \"telemetry\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"routing_table\" and r._field == \"peers\")\n    |> filter(fn: (r) => r.peer == \"${peer}\")\n    |> drop(columns: [\"peer\", \"session\"])"
    },
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"streams\" and r.peer == \"${peer}\")\n  |> drop(columns: [\"peer\", \"session\", \"protocol\"])\n  |> group(columns: [\"_time\"])\n  |> sum()\n  |> group()\n  |> rename(columns: {_value: \"streams\"})\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"session_info\" and r.peer == \"${peer}\" and r._field == \"boot_time\")\n  |> drop(columns: [\"session\", \"peer\"])\n  |> bottom(n: 1, columns: [\"_time\"])\n  |> map(fn: (r) => ({\n      r with _value: int(v: now()) - int(v: time(v: r._value))\n  }))\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Stream Protocols",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"streams\" and r.peer == \"${peer}\")\n  |> drop(columns: [\"peer\", \"session\", \"_start\", \"_stop\", \"_field\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"network_conns\" and r.peer == \"${peer}\" and r._field == \"conns\")\n  |> drop(columns: [\"peer\", \"session\"])\n  |> sort(columns: [\"_time\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_stats\")\n  |> filter(fn: (r) => r[\"peer\"] == \"${peer}\")\n  |> toFloat()\n  |> group(columns: [\"peer\", \"_time\", \"_field\"])\n  |> sum()\n  |> drop(columns: [\"peer\"])\n  |> group(columns: [\"_field\"])"
    }
   ]
  },
  {
   "title": "Bitswap Messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bitswap\" and r[\"peer\"] == \"${peer}\")\n  |> filter(fn: (r) => r._field == \"messages_in\" or r._field == \"messages_out\")\n  |> drop(columns: [\"peer\", \"session\"])\n  |> sort(columns: [\"_time\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"experimental/array\"\n\nfloatMap = (x) => float(v: x)\nzeroFilter = (x) => x > 0\nvalueMap = (x) => ({_value: x})\n\nrecord = from(bucket: \"telemetry\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"connections\" and r._field == \"latencies\" and r.peer == \"${peer}\")\n    |> last()\n    |> findRecord(fn: (key) => true, idx: 0)\n\nlatenciesString = strings.substring(v: record._value, start: 1, end: strings.strlen(v: record._value) - 1)\n\nlatencies = strings.split(v: latenciesString, t: \" \") \n                |> array.map(fn: floatMap)\n                |> array.filter(fn: zeroFilter)\n                |> array.map(fn: valueMap)\n\narray.from(rows: latencies)"
    }
   ]
  },
  {
   "title": "Bitswap Req/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"bitswap\" and (r._field == \"messages_in\" or r._field == \"messages_out\"))\n  |> filter(fn: (r) => r.peer == \"${peer}\")\n  |> aggregate.rate(every: 1m, unit: 1s, groupColumns: [\"_field\"])\n  |> drop(columns: [\"peer\", \"session\"])\n  "
    }
   ]
  },
  {
   "title": "Kademlia In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kademlia\" and r.peer == \"${peer}\" and r.direction == \"in\")\n  |> aggregate.rate(every: 1m, unit: 1s, groupColumns: [\"type\"])"
    }
   ]
  },
  {
   "title": "Kademlia Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kademlia\" and r.peer == \"${peer}\" and r.direction == \"out\")\n  |> aggregate.rate(every: 1m, unit: 1s, groupColumns: [\"type\"])"
    }
   ]
  },
  {
   "title": "Kademlia Handlers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kademlia_handler\")\n  |> filter(fn: (r) => r[\"peer\"] == \"${peer}\")\n  |> group(columns: [\"type\"])\n  |> aggregateWindow(every: duration(v: ( (uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)) / uint(v: 240) ) ), fn: mean)\n"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"resources\" and r[\"peer\"] == \"${peer}\")\n  |> drop(columns: [\"peer\", \"session\"])"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"storage\" and r.peer == \"${peer}\")\n  |> drop(columns: [\"peer\", \"session\"])"
    }
   ]
  }
 ]
}