// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/libp2p/go-libp2p/p2p/host/basic (interfaces: NAT)
//
// Generated by this command:
//
//	mockgen -build_flags=-tags=gomock -package basichost -destination mock_nat_test.go github.com/libp2p/go-libp2p/p2p/host/basic NAT
//

// Package basichost is a generated GoMock package.
package basichost

import (
	context "context"
	netip "net/netip"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNAT is a mock of NAT interface.
type MockNAT struct {
	ctrl     *gomock.Controller
	recorder *MockNATMockRecorder
	isgomock struct{}
}

// MockNATMockRecorder is the mock recorder for MockNAT.
type MockNATMockRecorder struct {
	mock *MockNAT
}

// NewMockNAT creates a new mock instance.
func NewMockNAT(ctrl *gomock.Controller) *MockNAT {
	mock := &MockNAT{ctrl: ctrl}
	mock.recorder = &MockNATMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNAT) EXPECT() *MockNATMockRecorder {
	return m.recorder
}

// AddMapping mocks base method.
func (m *MockNAT) AddMapping(ctx context.Context, protocol string, port int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMapping", ctx, protocol, port)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMapping indicates an expected call of AddMapping.
func (mr *MockNATMockRecorder) AddMapping(ctx, protocol, port any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMapping", reflect.TypeOf((*MockNAT)(nil).AddMapping), ctx, protocol, port)
}

// Close mocks base method.
func (m *MockNAT) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockNATMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockNAT)(nil).Close))
}

// GetMapping mocks base method.
func (m *MockNAT) GetMapping(protocol string, port int) (netip.AddrPort, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapping", protocol, port)
	ret0, _ := ret[0].(netip.AddrPort)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetMapping indicates an expected call of GetMapping.
func (mr *MockNATMockRecorder) GetMapping(protocol, port any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapping", reflect.TypeOf((*MockNAT)(nil).GetMapping), protocol, port)
}

// RemoveMapping mocks base method.
func (m *MockNAT) RemoveMapping(ctx context.Context, protocol string, port int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMapping", ctx, protocol, port)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMapping indicates an expected call of RemoveMapping.
func (mr *MockNATMockRecorder) RemoveMapping(ctx, protocol, port any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMapping", reflect.TypeOf((*MockNAT)(nil).RemoveMapping), ctx, protocol, port)
}
