// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: internal/pb/telemetry.proto

package pb

import (
	v1 "go.opentelemetry.io/proto/otlp/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_internal_pb_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_telemetry_proto_rawDescGZIP(), []int{0}
}

type GetSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The random UUID of this session
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_internal_pb_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetPropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertiesRequest) Reset() {
	*x = GetPropertiesRequest{}
	mi := &file_internal_pb_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertiesRequest) ProtoMessage() {}

func (x *GetPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertiesRequest.ProtoReflect.Descriptor instead.
func (*GetPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_telemetry_proto_rawDescGZIP(), []int{2}
}

type Property struct {
	state       protoimpl.MessageState   `protogen:"open.v1"`
	Scope       *v1.InstrumentationScope `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Name        string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Property_IntegerValue
	//	*Property_StringValue
	Value         isProperty_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_internal_pb_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_internal_pb_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *Property) GetScope() *v1.InstrumentationScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Property) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Property) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Property) GetValue() isProperty_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Property) GetIntegerValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Property_IntegerValue); ok {
			return x.IntegerValue
		}
	}
	return 0
}

func (x *Property) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Property_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

type isProperty_Value interface {
	isProperty_Value()
}

type Property_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,4,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type Property_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*Property_IntegerValue) isProperty_Value() {}

func (*Property_StringValue) isProperty_Value() {}

type GetMetricsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumberSince uint32                 `protobuf:"varint,1,opt,name=sequence_number_since,json=sequenceNumberSince,proto3" json:"sequence_number_since,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_internal_pb_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetricsRequest) GetSequenceNumberSince() uint32 {
	if x != nil {
		return x.SequenceNumberSince
	}
	return 0
}

type GetEventDescriptorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventDescriptorsRequest) Reset() {
	*x = GetEventDescriptorsRequest{}
	mi := &file_internal_pb_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventDescriptorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventDescriptorsRequest) ProtoMessage() {}

func (x *GetEventDescriptorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventDescriptorsRequest.ProtoReflect.Descriptor instead.
func (*GetEventDescriptorsRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_telemetry_proto_rawDescGZIP(), []int{5}
}

type EventDescriptor struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	EventId       uint32                   `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Scope         *v1.InstrumentationScope `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Name          string                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDescriptor) Reset() {
	*x = EventDescriptor{}
	mi := &file_internal_pb_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDescriptor) ProtoMessage() {}

func (x *EventDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDescriptor.ProtoReflect.Descriptor instead.
func (*EventDescriptor) Descriptor() ([]byte, []int) {
	return file_internal_pb_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *EventDescriptor) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EventDescriptor) GetScope() *v1.InstrumentationScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *EventDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetEventsRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// the sequence number of the first segment that should be returned.
	SequenceNumberSince uint32 `protobuf:"varint,2,opt,name=sequence_number_since,json=sequenceNumberSince,proto3" json:"sequence_number_since,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_internal_pb_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventsRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *GetEventsRequest) GetSequenceNumberSince() uint32 {
	if x != nil {
		return x.SequenceNumberSince
	}
	return 0
}

type GetStreamRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// The sequence number of the first segment that should be returned.
	SequenceNumberSince uint32 `protobuf:"varint,2,opt,name=sequence_number_since,json=sequenceNumberSince,proto3" json:"sequence_number_since,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetStreamRequest) Reset() {
	*x = GetStreamRequest{}
	mi := &file_internal_pb_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamRequest) ProtoMessage() {}

func (x *GetStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamRequest.ProtoReflect.Descriptor instead.
func (*GetStreamRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *GetStreamRequest) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *GetStreamRequest) GetSequenceNumberSince() uint32 {
	if x != nil {
		return x.SequenceNumberSince
	}
	return 0
}

type StreamSegment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber uint32                 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Data           []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamSegment) Reset() {
	*x = StreamSegment{}
	mi := &file_internal_pb_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSegment) ProtoMessage() {}

func (x *StreamSegment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSegment.ProtoReflect.Descriptor instead.
func (*StreamSegment) Descriptor() ([]byte, []int) {
	return file_internal_pb_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *StreamSegment) GetSequenceNumber() uint32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *StreamSegment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_pb_telemetry_proto protoreflect.FileDescriptor

const file_internal_pb_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/pb/telemetry.proto\x12\ttelemetry\x1a*opentelemetry/proto/common/v1/common.proto\"\x13\n" +
	"\x11GetSessionRequest\"(\n" +
	"\x12GetSessionResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x16\n" +
	"\x14GetPropertiesRequest\"\xe0\x01\n" +
	"\bProperty\x12I\n" +
	"\x05scope\x18\x01 \x01(\v23.opentelemetry.proto.common.v1.InstrumentationScopeR\x05scope\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\rinteger_value\x18\x04 \x01(\x03H\x00R\fintegerValue\x12#\n" +
	"\fstring_value\x18\x05 \x01(\tH\x00R\vstringValueB\a\n" +
	"\x05value\"G\n" +
	"\x11GetMetricsRequest\x122\n" +
	"\x15sequence_number_since\x18\x01 \x01(\rR\x13sequenceNumberSince\"\x1c\n" +
	"\x1aGetEventDescriptorsRequest\"\xad\x01\n" +
	"\x0fEventDescriptor\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12I\n" +
	"\x05scope\x18\x02 \x01(\v23.opentelemetry.proto.common.v1.InstrumentationScopeR\x05scope\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"a\n" +
	"\x10GetEventsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x122\n" +
	"\x15sequence_number_since\x18\x02 \x01(\rR\x13sequenceNumberSince\"c\n" +
	"\x10GetStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x122\n" +
	"\x15sequence_number_since\x18\x02 \x01(\rR\x13sequenceNumberSince\"L\n" +
	"\rStreamSegment\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\rR\x0esequenceNumber\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2\x89\x03\n" +
	"\tTelemetry\x12I\n" +
	"\n" +
	"GetSession\x12\x1c.telemetry.GetSessionRequest\x1a\x1d.telemetry.GetSessionResponse\x12G\n" +
	"\rGetProperties\x12\x1f.telemetry.GetPropertiesRequest\x1a\x13.telemetry.Property0\x01\x12F\n" +
	"\n" +
	"GetMetrics\x12\x1c.telemetry.GetMetricsRequest\x1a\x18.telemetry.StreamSegment0\x01\x12Z\n" +
	"\x13GetEventDescriptors\x12%.telemetry.GetEventDescriptorsRequest\x1a\x1a.telemetry.EventDescriptor0\x01\x12D\n" +
	"\tGetEvents\x12\x1b.telemetry.GetEventsRequest\x1a\x18.telemetry.StreamSegment0\x01B\rZ\vinternal/pbb\x06proto3"

var (
	file_internal_pb_telemetry_proto_rawDescOnce sync.Once
	file_internal_pb_telemetry_proto_rawDescData []byte
)

func file_internal_pb_telemetry_proto_rawDescGZIP() []byte {
	file_internal_pb_telemetry_proto_rawDescOnce.Do(func() {
		file_internal_pb_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_telemetry_proto_rawDesc), len(file_internal_pb_telemetry_proto_rawDesc)))
	})
	return file_internal_pb_telemetry_proto_rawDescData
}

var file_internal_pb_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_pb_telemetry_proto_goTypes = []any{
	(*GetSessionRequest)(nil),          // 0: telemetry.GetSessionRequest
	(*GetSessionResponse)(nil),         // 1: telemetry.GetSessionResponse
	(*GetPropertiesRequest)(nil),       // 2: telemetry.GetPropertiesRequest
	(*Property)(nil),                   // 3: telemetry.Property
	(*GetMetricsRequest)(nil),          // 4: telemetry.GetMetricsRequest
	(*GetEventDescriptorsRequest)(nil), // 5: telemetry.GetEventDescriptorsRequest
	(*EventDescriptor)(nil),            // 6: telemetry.EventDescriptor
	(*GetEventsRequest)(nil),           // 7: telemetry.GetEventsRequest
	(*GetStreamRequest)(nil),           // 8: telemetry.GetStreamRequest
	(*StreamSegment)(nil),              // 9: telemetry.StreamSegment
	(*v1.InstrumentationScope)(nil),    // 10: opentelemetry.proto.common.v1.InstrumentationScope
}
var file_internal_pb_telemetry_proto_depIdxs = []int32{
	10, // 0: telemetry.Property.scope:type_name -> opentelemetry.proto.common.v1.InstrumentationScope
	10, // 1: telemetry.EventDescriptor.scope:type_name -> opentelemetry.proto.common.v1.InstrumentationScope
	0,  // 2: telemetry.Telemetry.GetSession:input_type -> telemetry.GetSessionRequest
	2,  // 3: telemetry.Telemetry.GetProperties:input_type -> telemetry.GetPropertiesRequest
	4,  // 4: telemetry.Telemetry.GetMetrics:input_type -> telemetry.GetMetricsRequest
	5,  // 5: telemetry.Telemetry.GetEventDescriptors:input_type -> telemetry.GetEventDescriptorsRequest
	7,  // 6: telemetry.Telemetry.GetEvents:input_type -> telemetry.GetEventsRequest
	1,  // 7: telemetry.Telemetry.GetSession:output_type -> telemetry.GetSessionResponse
	3,  // 8: telemetry.Telemetry.GetProperties:output_type -> telemetry.Property
	9,  // 9: telemetry.Telemetry.GetMetrics:output_type -> telemetry.StreamSegment
	6,  // 10: telemetry.Telemetry.GetEventDescriptors:output_type -> telemetry.EventDescriptor
	9,  // 11: telemetry.Telemetry.GetEvents:output_type -> telemetry.StreamSegment
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_pb_telemetry_proto_init() }
func file_internal_pb_telemetry_proto_init() {
	if File_internal_pb_telemetry_proto != nil {
		return
	}
	file_internal_pb_telemetry_proto_msgTypes[3].OneofWrappers = []any{
		(*Property_IntegerValue)(nil),
		(*Property_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_telemetry_proto_rawDesc), len(file_internal_pb_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_telemetry_proto_goTypes,
		DependencyIndexes: file_internal_pb_telemetry_proto_depIdxs,
		MessageInfos:      file_internal_pb_telemetry_proto_msgTypes,
	}.Build()
	File_internal_pb_telemetry_proto = out.File
	file_internal_pb_telemetry_proto_goTypes = nil
	file_internal_pb_telemetry_proto_depIdxs = nil
}
