apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-docs
  labels:
    {{- include "ipfs-telemetry.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
spec:
  selector:
    matchLabels:
      {{- include "ipfs-telemetry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: docs
  template:
    metadata:
      labels:
        {{- include "ipfs-telemetry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: docs
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Release.Name }}-docs
          image: "{{ .Values.services.docs.image.repository }}:{{ .Values.services.docs.image.tag }}"
          imagePullPolicy: {{ .Values.services.docs.image.pullPolicy }}
          {{- with .Values.services.docs.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP