---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-exporter-s3-pg
  labels:
    {{- include "ipfs-telemetry.labels" . | nindent 4 }}
    app.kubernetes.io/component: exporter-s3-pg
spec:
  selector:
    matchLabels:
      {{- include "ipfs-telemetry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: exporter-s3-pg
  template:
    metadata:
      labels:
        {{- include "ipfs-telemetry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: exporter-s3-pg
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Release.Name }}-exporter-s3-pg
          image: {{ include "ipfs-telemetry.image.backend.image" . | quote }}
          imagePullPolicy: {{ include "ipfs-telemetry.image.backend.pullPolicy" . | quote }}
          command: ["poetry", "run", "python", "-m", "apps.exporter-s3-pg"]
          {{- with .Values.services.exporterS3Pg.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "ipfs-telemetry.env" . | nindent 12 }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP