{{- if .Values.services.webapi.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-webapi
  labels:
    {{- include "ipfs-telemetry.labels" . | nindent 4 }}
    {{- with .Values.services.webapi.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{ with .Values.services.webapi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.services.webapi.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.services.webapi.ingress.hostname }}
      http:
        paths:
          - pathType: Prefix
            path: "/api/v0/"
            backend:
              service:
                name: {{ .Release.Name }}-webapi
                port:
                  name: http
{{- end }}