services:
  probe:
    image: ghcr.io/diogo464/telemetry:latest
    command: probe
  orchestrator:
    image: ghcr.io/diogo464/telemetry:latest
    command: orchestrator
    environment:
      ORCHESTRATOR_PROMETHEUS_ADDRESS: ":9090"
      ORCHESTRATOR_INFLUXDB_ADDRESS: "http://influxdb:8086"
      ORCHESTRATOR_INFLUXDB_TOKEN: "token"
      ORCHESTRATOR_INFLUXDB_ORG: "adc"
      ORCHESTRATOR_INFLUXDB_BUCKET: "probing"
      ORCHESTRATOR_ADDRESS: ":5600"
      ORCHESTRATOR_PROBES: "probe:4640"
    depends_on:
      - probe
      - influxdb
      - prometheus
  grafana:
    image: docker.io/grafana/grafana:latest
    volumes:
      - telemetry-grafana:/var/lib/grafana
      - ./grafana-datasources:/etc/grafana/provisioning/datasources/:Z
      - ./grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:Z
      - ./grafana-dashboards/:/var/lib/grafana/dashboards:Z
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
  influxdb:
    image: docker.io/influxdb:latest
    volumes:
      - telemetry-influxdb:/var/lib/influxdb2
      - ./influxdb_setup.sh:/docker-entrypoint-initdb.d/influxdb_setup.sh:Z
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "user"
      DOCKER_INFLUXDB_INIT_PASSWORD: "password"
      DOCKER_INFLUXDB_INIT_ORG: "adc"
      DOCKER_INFLUXDB_INIT_BUCKET: "probing"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "token"
  prometheus:
    image: docker.io/prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
volumes:
  telemetry-grafana: {}
  telemetry-influxdb: {}
