---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  labels:
    app.kubernetes.io/component: docs
spec:
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
        app.kubernetes.io/component: docs
    spec:
      containers:
        - name: docs
          image: ghcr.io/diogo464/ipfs-telemetry/docs:main
          imagePullPolicy: Always
          resources:
            requests:
              memory: "16Mi"
              cpu: "0m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: docs
  labels:
    app.kubernetes.io/component: docs
spec:
  selector:
    app: docs
  ports:
    - name: http
      port: 80
      targetPort: http
