---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter-vm
  labels:
    app.kubernetes.io/component: exporter-vm
spec:
  selector:
    matchLabels:
      app: exporter-vm
  template:
    metadata:
      labels:
        app: exporter-vm
        app.kubernetes.io/component: exporter-vm
    spec:
      initContainers:
        - name: init
          image: ghcr.io/diogo464/ipfs-telemetry/backend:main
          imagePullPolicy: Always
          command: ["poetry", "run", "python", "-m", "backend.job.init"]
          envFrom:
            - configMapRef:
                name: envconfig
      containers:
        - name: exporter-vm
          image: ghcr.io/diogo464/ipfs-telemetry/backend:main
          imagePullPolicy: Always
          command: ["poetry", "run", "python", "-m", "component.exporter-vm"]
          resources:
            requests:
              memory: "96Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: envconfig
