---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app.kubernetes.io/component: webapi
spec:
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
        app.kubernetes.io/component: webapi
    spec:
      initContainers:
        - name: init
          image: ghcr.io/diogo464/ipfs-telemetry/backend:main
          imagePullPolicy: Always
          command: ["poetry", "run", "python", "-m", "backend.job.init"]
          envFrom:
            - configMapRef:
                name: envconfig
      containers:
        - name: webapi
          image: ghcr.io/diogo464/ipfs-telemetry/backend:main
          imagePullPolicy: Always
          command:
            ["poetry", "run", "python", "-m", "webapi", "--host", "0.0.0.0"]
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: envconfig
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
spec:
  selector:
    app: webapi
  ports:
    - name: http
      port: 80
      targetPort: http
