apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  ingress:
    enabled: True
    ingressClassName: nginx
    pathType: Prefix
    path: "/"
    hostname: grafana.minikube.lan
