apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: ghcr.io/diogo464/ipfs-telemetry/ipfs-bot
    newName: localhost:5000/ipfs-bot
    newTag: latest
  - name: ghcr.io/diogo464/ipfs-telemetry/monitor
    newName: localhost:5000/monitor
    newTag: latest
  - name: ghcr.io/diogo464/ipfs-telemetry/crawler
    newName: localhost:5000/crawler
    newTag: latest
  - name: ghcr.io/diogo464/ipfs-telemetry/backend
    newName: localhost:5000/backend
    newTag: latest

components:
  # Dependencies
  - ../../components/dependencies/repos
  - ../../components/dependencies/redis
  - ../../components/dependencies/nats
  - ../../components/dependencies/victoria-metrics
  - ../../components/dependencies/timescaledb
  - ../../components/dependencies/grafana-operator
  - ../../components/dependencies/prometheus-operator
  # Application Components
  - ../../components/ipfs-bot
  - ../../components/grafana
  - ../../components/prometheus

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: ipfs-bot

patchesStrategicMerge:
  - grafana-ingress.yaml
  - monitor-collect-interval.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: ipfs-telemetry
      app.kubernetes.io/instance: ipfs-telemetry-dev
