name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Setup protoc
      run: sudo apt install golang-goprotobuf-dev

    - name: Build tools
      run: make tools

    - name: Build proto
      run: make proto

    - name: Build
      run: make build

    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        registry: ghcr.io
        username: diogo464
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container
      uses: docker/build-push-action@v2.10.0
      with:
        context: .
        file: deploy/telemetry/Dockerfile
        push: true
        tags: ghcr.io/diogo464/telemetry:latest
        
    - name: Upload proto files
      uses: actions/upload-artifact@v3.0.0
      with:
        name: proto-files
        path: pkg/proto
