apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  client:
    preferService: true
  ingress:
    enabled: True
    pathType: Prefix
    path: "/"
    hostname: "grafana.minikube.lan"
  config:
    log:
      mode: "console"
      level: "error"
    log.frontend:
      enabled: true
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
  service:
    name: grafana-service
    labels:
      app: grafana
      type: grafana-service
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [telemetry] }
  resources:
    # Optionally specify container resources
    limits:
      cpu: 400m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 100Mi
