apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchExpressions:
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - ipfs-telemetry
  podMonitorSelector:
    matchExpressions:
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - ipfs-telemetry
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
